#
# Makefile for Chromeos Supplied Third-Party device drivers
#

obj-$(CONFIG_GOBI)      += gobi/QCSerial2k/
obj-$(CONFIG_GOBI)      += gobi/QCUSBNet2k/
obj-$(CONFIG_GOBI)      += gobi/QCQMI/

# This is a stupid trick to get kbuild to create chromeos/built-in.o
obj- += foo.o
