#
# Makefile for Chromeos Supplied Third-Party device drivers
#

obj-$(CONFIG_GOBI_QCSERIAL) += gobi/QCSerial2k/
obj-$(CONFIG_GOBI_USBNET)   += gobi/QCUSBNet2k/

# This is a stupid trick to get kbuild to create chromeos/built-in.o
obj- += foo.o
